spring.application.name=scheduler

spring.datasource.url=jdbc:postgresql://localhost:5432/scheduler
spring.datasource.username=postgres
spring.datasource.password=assessmentdb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=elchi301ken@gmail.com
spring.mail.password=0913 1175
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.jwt.secret=XbT7sYXUYHidZDAwbX2/7T+VFXx87SikXO07J9MeOnVOtinymyWMrQhVF+iy/egKGluxRagdaQ5kNUUY0jEeTw==
app.jwt.expiration-minutes=60
app.base-url=http://localhost:8080

openai.api.key=${OPENAI_API_KEY}